#!/usr/bin/env node
import { spawnSync } from 'node:child_process';

const B={a1:'lab/a1-complete',a2b:'lab/a2-base',a2d:'lab/a2-thang',a2g:'lab/a2-ba-pha',a3b:'lab/a3-base',a3d:'lab/a3-giao-thang',a3g:'lab/a3-phong-van',a3c:'lab/a3-complete'};
const S={a2:['src/pricing/types.ts','src/pricing/calc-fee.ts','src/pricing/validate.ts','src/db/seed.sql','web/index.html','src/pricing/__tests__/shipping.test.ts'],a3:['src/pricing','web/index.html']};
function run(c,a=[],cap=false){const r=spawnSync(c,a,{encoding:'utf8',stdio:cap?'pipe':'inherit'});if(r.status!==0)throw Error(`Không thể chạy ${c}.`);return cap?r.stdout.trimEnd():''}
const git=(a,c=false)=>run('git',a,c), exists=n=>spawnSync('git',['show-ref','--verify','--quiet',`refs/heads/${n}`]).status===0;
const cur=()=>git(['branch','--show-current'],true), changed=()=>git(['status','--porcelain','--untracked-files=all'],true).split('\n').filter(Boolean).map(x=>x.slice(3)).filter(x=>x!=='.agents/mcp_config.json');
const stop=m=>{throw Error(m)}, clean=()=>{const f=changed();if(f.length)stop(`Đang có thay đổi chưa được giữ lại: ${f.join(', ')}. Helper không tự xoá hoặc stash.`)}, branch=n=>{if(cur()!==n)stop(`Cần ở ${n}, hiện đang ở ${cur()||'(không có tên)'}.`)}, missing=ns=>{const f=ns.filter(exists);if(f.length)stop(`Checkpoint đã tồn tại: ${f.join(', ')}. Helper dừng để không ghi đè.`)};
const test=()=>{console.log('Đang kiểm tra repo trước khi lưu checkpoint…');run('npm',['test'])};
function commit(msg,scope){const f=changed();if(!f.length)stop('Không có thay đổi nào để lưu.');if(scope){const bad=f.filter(x=>!scope.some(p=>x===p||x.startsWith(`${p}/`)));if(bad.length)stop(`Có thay đổi ngoài phạm vi bài: ${bad.join(', ')}. Helper dừng.`)}git(['add','--all','--',...(scope??['.']),':(exclude).agents/mcp_config.json']);git(['-c','user.name=AI Academy Lab','-c','user.email=lab@ai-academy.local','commit','-m',msg])}
const save=(b,msg,s)=>{branch(b);test();commit(msg,s);console.log(`Đã lưu ${b}; test đạt và working tree sạch.`)};
const newBranch=(n,from)=>{missing([n]);git(['switch','-c',n,from])};
function compare(l,r,m){if(!exists(l)||!exists(r))stop(`Chưa đủ hai checkpoint ${l} và ${r}.`);clean();console.log(`So sánh ${l} ↔ ${r}`);console.log(git(['diff','--name-only',l,r],true)||'(Không có file khác nhau)');console.log(git(['diff','--stat',l,r],true)||'(Không có thống kê thay đổi)');console.log('Các checkpoint chỉ lưu sau khi test đạt; helper không đổi trạng thái khi so sánh.');console.log(m==='a2'?'Đối chiếu thêm type, surcharge, validation, seed, web và test.':'Đối chiếu thêm ba quyết định nghiệp vụ, context/spec, file và test.')}
function main(){run('git',['rev-parse','--show-toplevel'],true);const[a,m,x]=process.argv.slice(2);if(a==='checkpoint'&&m==='a1'){missing([B.a1]);const bad=changed().filter(f=>!f.startsWith('tools/report/'));if(bad.length)stop(`A1 chỉ được thay đổi tools/report/: ${bad.join(', ')}`);test();newBranch(B.a1,'HEAD');commit('lab: hoàn thành A1',['tools/report']);console.log('A1 đã lưu sạch.');return}if(a==='prepare'&&m==='a2'){clean();branch(B.a1);missing([B.a2b,B.a2d,B.a2g]);git(['branch',B.a2b,'HEAD']);newBranch(B.a2d,B.a2b);console.log('Đã mở A2 Vòng 1 từ điểm gốc chung.');return}if(a==='save'&&m==='a2'&&x==='direct')return save(B.a2d,'lab: lưu A2 vòng giao thẳng',S.a2);if(a==='start'&&m==='a2'&&x==='guided'){clean();branch(B.a2d);newBranch(B.a2g,B.a2b);console.log('Đã mở A2 Vòng ba pha từ cùng điểm gốc.');return}if(a==='save'&&m==='a2'&&x==='guided')return save(B.a2g,'lab: lưu A2 vòng ba pha',S.a2);if(a==='compare'&&m==='a2')return compare(B.a2d,B.a2g,'a2');if(a==='prepare'&&m==='a3'){clean();branch(B.a2g);missing([B.a3b,B.a3d,B.a3g,B.a3c]);git(['branch',B.a3b,'HEAD']);newBranch(B.a3d,B.a3b);console.log('Đã mở A3 Vòng giao thẳng từ A2 ba pha.');return}if(a==='save'&&m==='a3'&&x==='direct')return save(B.a3d,'lab: lưu A3 vòng giao thẳng',S.a3);if(a==='start'&&m==='a3'&&x==='guided'){clean();branch(B.a3d);newBranch(B.a3g,B.a3b);console.log('Đã mở A3 Vòng phỏng vấn từ cùng điểm gốc.');return}if(a==='save'&&m==='a3'&&x==='guided')return save(B.a3g,'lab: lưu A3 vòng phỏng vấn',S.a3);if(a==='compare'&&m==='a3')return compare(B.a3d,B.a3g,'a3');if(a==='complete'&&m==='a3'){branch(B.a3g);test();missing([B.a3c]);newBranch(B.a3c,'HEAD');if(changed().length)commit('lab: hoàn thành A3',S.a3);console.log('Đã hoàn thành A3 và tạo checkpoint cuối.');return}stop('Cú pháp không hợp lệ.')}
try{main()}catch(e){console.error(`\nDỪNG: ${e.message}`);process.exit(1)}
